### ISSUE TITLE
Word count doesn't count first word of line

### ISSUE THREAD

**Issue by joelschmid91** [damyon/moodle-atto_count#6] opened 2017-04-27 15:33 UTC
The plugin doesn't count the first word starting from the second line on. See image: 
<img width="484" alt="screen shot 2017-04-27 at 17 28 55" src="https://cloud.githubusercontent.com/assets/20297204/25491237/a3dd10a4-2b6f-11e7-9cef-94f461d99ce5.png">

It would be great if this could get fixed asap!

**Comment by damyon** [comment] 2017-04-28 02:02
The point of this plugin is that it does not count the words itself - but uses the Moodle php function to do so which ensures that the results are consistent with the word limit feature in assignment etc. If there is a mistake in the way Moodle counts words, please file a bug on the Moodle tracker.

**Comment by joelschmid91** [comment] 2017-05-08 08:25
What function is it based on? Can you provide some more details so I can create a bug report on the Moodle tracker?

**Comment by peterspicer-catalyst** [comment] 2017-08-30 13:32
It's a bug in moodlelib.php, in count_words() though it only affects if the preceding line doesn't have punctuation at the end.

More details: https://tracker.moodle.org/projects/MDL/issues/MDL-59907

**Comment by adpe** [comment] 2017-12-20 08:02
What's happened with this Issue/Tracker?

**Comment by adpe** [comment] 2018-06-12 14:17
Hello @peterspicer-catalyst 

The Tracker doesn't exists anymore. Do you know what's going on with this bug?

**Comment by peterspicer-catalyst** [comment] 2018-06-12 14:20
The URL structure has changed in JIRA since then - https://tracker.moodle.org/browse/MDL-59989 shows the issue is exactly where it was before.

Unfortunately I haven't had time to submit a patch - but there is a larger problem: this is backward compatibility breaking behaviour and potentially affects student grading.

**Comment by rujul04** [comment] 2019-03-06 05:35
I have fixed this issue by using external lib in this plugin.
https://github.com/mtibben/html2text

**Comment by lucaboesch** [comment] 2021-09-02 15:52
I can confirm this is fixed.
<img width="939" alt="6_fixed" src="https://user-images.githubusercontent.com/377279/131876339-6f8f6934-c8e2-46ee-b283-ff2964182dcb.png">
In core, without the external lib mentioned by @ratedcrypto.

Best,
Luca

**Comment by damyon** [comment] 2021-09-03 04:05
Thanks for confirming Luca, closing this issue.

**Closed by damyon** 2021-09-03 04:05 UTC
